### ISSUE TITLE
Library subdirectories incompatible with chef-client

### ISSUE THREAD

**Issue by gormeroth** [target/f5-bigip-cookbook#9] opened 2016-02-19 06:10 UTC
f5-bigip cookbook does not work with chef-client 12 due to non-support for library subdirectories

**Comment by jmccann** [comment] 2016-02-19 14:45
My understanding is that this has been supported since https://github.com/chef/chef/pull/2129

Are you running into issues?

**Comment by gkra** [comment] 2016-02-19 19:05
When attempting to upload the cookbook to our chef server, using either `knife cookbook upload` or `berks upload` (ChefDK 0.10.0) it appears that any directories under `libraries` are omitted. We're running Chef Server 12.0.8 (based on the RPM version of chef-server-core).

As a result, when a cookbook is downloaded from the server (for example, via `knife cookbook download`) it lacks the `load_balancer` tree under `libraries`. Likewise, when browsing the cookbook in the org via Chef Manage, the `load_balancer` tree is missing.

Is it just that our Chef Server is not a recent enough version? I'd thought this issue was merged for 12.0.0...

**Comment by gkra** [comment] 2016-02-23 00:40
@jmccann To put a point on it, is this cookbook intended to be executed by `chef-client` in a typical client/server Chef environment, or is it used in a standalone `chef-solo` environment?

**Comment by jmccann** [comment] 2016-02-23 01:09
This cookbook is intended to be used in a client/server environment but I haven't used it in such an environment yet.

Trying to upload the cookbook to my Org on our Chef server I do see it is not uploading all the files though they do all get uploaded properly to supermarket when sharing it to there.

I will investigate more as to if this is a bug with Chef 12 server or expected behavior.

Thanks!

**Comment by jmccann** [comment] 2016-02-23 01:18
I created https://github.com/chef/chef-server/issues/751 to try and get more insight from Chef. :smile:

**Comment by gkra** [comment] 2016-02-29 18:24
One possibility would be to bundle the `load_balancer` tree as a gem, as that's basically what it is, if my understanding of the code is correct... It would complicate code maintenance a bit, as you'd have a separate project that this cookbook would depend on, but then you could embed the .gem as you do the F5 iControl gem, and it would get around the Chef Server limitation of not supporting subtrees in libraries.

**Comment by Alowishus** [comment] 2016-02-29 18:46
Curious how this is being used internally at Target then... you say it's intended to be used in client/server, but given the issue being discussed here it seems that's not (currently) tenable.  @jmccann can you shed some light?

**Comment by nickayoung** [comment] 2016-03-16 00:12
I am having this same issue, anyone able to get past it?

**Comment by jmccann** [comment] 2016-03-17 13:43
This should be addressed by e3736f55c854918ba332447778dc7e6f0f066a9d now.

**Closed by jmccann** 2016-03-17 13:43 UTC
